name: ACM SIGCSE 2016
markdown: kramdown
highlighter: pygments

purple: "#662D91"
orange: "#FF892A"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "lefthandlogo" # was "base"
